# -*- coding: utf-8 -*-
"""2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14lqwqrS-_iCJnAXhSLTCG8mR1SFDYEJE
"""

import csv
with open("funcs.csv") as funcs:
    reader = csv.reader(funcs)
    data_read = [column for column in funcs]
    data_read = data_read[1:]

def data_prep(data_read):
    for i in range(len(data_read)):
          data_read[i]=data_read[i][:-1]

    split_data = [i.split(';') for i in data_read]

    return split_data
  
def dep_items(data_read):
    split_data = [i.split(';') for i in data_read]
    departments = []
    for i in range(len(split_data)):
        departments.append(split_data[i][2])  
    
    return  set(departments)

col = len(dep_items(data_read))+1
row = 5
l_i_l =[[0 for col in range(col)] for row in range(row)]

k= list(dep_items(data_read))
l = data_prep(data_read)

l_i_l[2][7] = 'minwage'
l_i_l[1][7] = "personel"
l_i_l[3][7] = 'maxwage'
l_i_l[4][7] = 'meanwage'
l_i_l[0][7] = 'department'

def report(data_read):

    import csv
    with open("funcs.csv") as funcs:
       reader = csv.reader(funcs)
       data_read = [column for column in funcs]
       data_read = data_read[1:]

    def data_prep(data_read):
        for i in range(len(data_read)):
            data_read[i]=data_read[i][:-1]

    split_data = [i.split(';') for i in data_read]

    return split_data
  
    def dep_items(data_read):
        split_data = [i.split(';') for i in data_read]
        departments = []
        for i in range(len(split_data)):
            departments.append(split_data[i][2])  
    
        return  set(departments)

    col = len(dep_items(data_read))+1
    row = 5
    l_i_l =[[0 for col in range(col)] for row in range(row)]

    k= list(dep_items(data_read))
    l = data_prep(data_read)

    l_i_l[2][7] = 'minwage'
    l_i_l[1][7] = "personel"
    l_i_l[3][7] = 'maxwage'
    l_i_l[4][7] = 'meanwage'
    l_i_l[0][7] = 'department'

    for j in range(len(k)): # personel
   
         for i in range(len(l)):
      
              if l[i][2] == k[j]:
          
                  l_i_l[1][j] += 1
  

    for j in range(len(k)): # department add
   
         for i in range(len(l)):
          
              l_i_l[0][j] = k[j]
         l_i_l[2][j] = 10**6    
         l[i][4] = int(l[i][4])
       

    for j in range(len(k)):  # min wage
   
         for i in range(len(l)):
       
             if l[i][2] == k[j]:

                if l[i][4] < l_i_l[3][j]:

                   l_i_l[2][j] = l[i][4] 

    for j in range(len(k)): # mean wage
   
         for i in range(len(l)):
      
            if l[i][2] == k[j]:
          
                   l_i_l[4][j] = + l[i][4]
            
    
            l_i_l[4][j] = round(l_i_l[4][j]/l_i_l[1][j],1)

    for j in range(len(k)):     # max wage
   
        for i in range(len(l)):
       
           if l[i][2] == k[j]:

               if l[i][4] < l_i_l[3][j]:

                    l_i_l[2][j] = l[i][4] 
      
    return l_i_

def save_report(data_read):

    # save report
    
    final = report(data_read)

    with open('report.csv', 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
              

if __name__ == '__main__':
    my_file = 'funcs.csv'
    my_data = csv_read(my_file)
    report(my_data)

def choose_option():
    
    print(
        '''
    Выбрать:
    1. Вывести все отделы
    2. Вывести в консоль сводный отчёт по отделам: название, численность, минимальная и максимальная, средняя з/п
    3. Сохранить сводный отчёт  в виде csv-файла.
        '''
    )

    option = ''
    options = {'1': dep_items(data_read), '2': report(data_read),
               '3': save_report(data_read)}
    while option not in options:
        print('Введите {} / {} / {}'.format(*options), "")
        option = input()
    options[option]()